name: Playwright Tests for Blazor
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    # Fix xUnit dependency conflict
    - name: Fix package dependencies
      run: |
        dotnet add Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj package xunit.extensibility.core --version 2.8.0
    
    # Selectively restore the test projects
    - name: Restore test projects
      run: |
        dotnet restore Test.Components/Test.Components.csproj
        dotnet restore Test.BUnit.UnitTests/Test.BUnit.UnitTests.csproj
        dotnet restore Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj
        dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host/Test.BrowserBased.Host.csproj
        dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host.Client/Test.BrowserBased.Host.Client.csproj
    
    - name: Build Test.BrowserBased.UnitE2ETests
      run: dotnet build Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore
    
    - name: Install Playwright Browsers
      run: |
        cd Test.BrowserBased.UnitE2ETests
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install --with-deps
    
    - name: Run Playwright tests
      run: |
        cd Test.BrowserBased.UnitE2ETests
        npx playwright test --reporter=html --output=Test.BrowserBased.UnitE2ETests/playwright-report/

        
    - name: List files in the directory
      run: ls -R Test.BrowserBased.UnitE2ETests/playwright-report/
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: Test.BrowserBased.UnitE2ETests/playwright-report/
        retention-days: 30