name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
#    - name: Build & Install
      # run: dotnet build
      
# Fix xUnit dependency conflict
      - name: Fix package dependencies
        run: |
          dotnet add Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj package xunit.extensibility.core --version 2.8.0
    
    # Selectively restore the test projects
    # qqqq may not need all of them as may happen in test step do we want to fail early? we will have dependabot yml too so this will need to run first
      - name: Restore test projects
        run: |
          dotnet restore Test.Components/Test.Components.csproj
          dotnet restore Test.BUnit.UnitTests/Test.BUnit.UnitTests.csproj
          dotnet restore Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj
          dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host/Test.BrowserBased.Host.csproj
          dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host.Client/Test.BrowserBased.Host.Client.csproj
    
      - name: Build & Install
        run: | 
          dotnet build Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore
          
      #check if fails early
      - name: Ensure browsers are installed
        run: pwsh Test.BrowserBased.UnitE2ETests/bin/Debug/net8.0/playwright.ps1 install --with-deps
        
      #- name: Run your tests
      #  run: dotnet test --filter "Category!=LocalOnly & Category!=HeadlessFalse" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity detailed
      
      # We dont want to do it per test but lets see
      - name: Run MainNavigation
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.MainNavigation" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (chromium, True, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(chromium,True,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (chromium, False, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(chromium,False,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (chromium, True, Mobile)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(chromium,True,Mobile)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (chromium, False, Mobile)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(chromium,False,Mobile)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (firefox, True, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(firefox,True,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (firefox, False, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(firefox,False,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (firefox, True, Mobile)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(firefox,True,Mobile)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (firefox, False, Mobile)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(firefox,False,Mobile)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (webkit, True, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(webkit,True,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (webkit, False, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(webkit,False,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (webkit, True, Mobile)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(webkit,True,Mobile)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_Loads_Correctly (webkit, False, Mobile)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_Loads_Correctly(webkit,False,Mobile)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_InteractivityIsCorrectlySimulated (chromium, True, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_InteractivityIsCorrectlySimulated(chromium,True,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_InteractivityIsCorrectlySimulated (chromium, False, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_InteractivityIsCorrectlySimulated(chromium,False,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_InteractivityIsCorrectlySimulated (chromium, True, Mobile)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_InteractivityIsCorrectlySimulated(chromium,True,Mobile)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_InteractivityIsCorrectlySimulated (chromium, False, Mobile)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_InteractivityIsCorrectlySimulated(chromium,False,Mobile)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      - name: Run Page_InteractivityIsCorrectlySimulated (firefox, True, Desktop)
        run: dotnet test --filter "FullyQualifiedName~Test.BrowserBased.UnitE2ETests.Tests.BrowserBasedTests.Page_InteractivityIsCorrectlySimulated(firefox,True,Desktop)" Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
      #run: |
       #   cd Test.BrowserBased.UnitE2ETests
       #   dotnet test --no-restore
          
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: Test.BrowserBased.UnitE2ETests/playwright-report/
          retention-days: 30
