name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
#    - name: Build & Install
      # run: dotnet build
      
# Fix xUnit dependency conflict
      - name: Fix package dependencies
        run: |
          dotnet add Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj package xunit.extensibility.core --version 2.8.0
    
    # Selectively restore the test projects
    # qqqq may not need all of them as may happen in test step do we want to fail early? we will have dependabot yml too so this will need to run first
      - name: Restore test projects
        run: |
          dotnet restore Test.Components/Test.Components.csproj
          dotnet restore Test.BUnit.UnitTests/Test.BUnit.UnitTests.csproj
          dotnet restore Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj
          dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host/Test.BrowserBased.Host.csproj
          dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host.Client/Test.BrowserBased.Host.Client.csproj
    
      - name: Build & Install
        run: | 
          dotnet build Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore
          
      #check if fails early
      - name: Ensure browsers are installed
        run: pwsh Test.BrowserBased.UnitE2ETests/bin/Debug/net8.0/playwright.ps1 install --with-deps
      # - name: Playwright test run excepted filtered
        # run : dotnet test --filter "Category!=LocalOnly & Category!=HeadlessFalse"  Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal      
      
      - name: Playwright test run excepted filtered
        run: dotnet test --filter "Category!=LocalOnly & Category!=HeadlessFalse" Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity verbose
        working-directory: Test.BrowserBased.UnitE2ETests

      - uses: actions/upload-artifact@v4
        if: Always() 
        #${{ !cancelled() }} qqqq put back in
        with:
          name: playwright-report
          path: playwright-report/
          # want it here 
          # path: Test.BrowserBased.UnitE2ETests/playwright-report/
          retention-days: 30
