name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      
    # Fix xUnit dependency conflict
      - name: Fix package dependencies
        run: |
          dotnet add Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj package xunit.extensibility.core --version 2.8.0
    
    # Selectively restore the test projects
      - name: Restore test projects
        run: |
          dotnet restore Test.Components/Test.Components.csproj
          dotnet restore Test.BUnit.UnitTests/Test.BUnit.UnitTests.csproj
          dotnet restore Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj
          dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host/Test.BrowserBased.Host.csproj
          dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host.Client/Test.BrowserBased.Host.Client.csproj
    
      - name: Build & Install
        run: | 
          dotnet build Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore

      - name: Ensure browsers are installed
        run: pwsh Test.BrowserBased.UnitE2ETests/bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Playwright test run excepted filtered
        run: dotnet test --filter "Category!=LocalOnly & Category!=HeadlessFalse" Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
        working-directory: Test.BrowserBased.UnitE2ETests
        
      - name: Debug List All Files in Test Project
        if: always()
        run: ls -R Test.BrowserBased.UnitE2ETests || true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: Test.BrowserBased.UnitE2ETests/playwright-report/
          retention-days: 30
