name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  ## test.BUnit.UnitTests
  ## qqqq bunit-lh-tests:
  bunit-shared-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
      
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        
        - name: Restore test projects
          run: |
            dotnet restore Test.Components/Test.Components.csproj
            dotnet restore Package.Shared.BlazorComponents.UnitTests/Package.Shared.BlazorComponents.UnitTests.csproj
            dotnet restore Package.Shared.BlazorComponents/Package.Shared.BlazorComponents.csproj
            dotnet restore Package.Shared.Entities/Package.Shared.Entities.csproj
            dotnet restore Package.Shared.Services/Package.Shared.Services.csproj
            
        - name: Build & Install
          run: | 
            dotnet build Test.Components/Test.Components.csproj --no-restore
            dotnet build Package.Shared.BlazorComponents/Package.Shared.BlazorComponents.UnitTests.csproj --no-restore
            dotnet build Package.Shared.BlazorComponents/Package.Shared.BlazorComponents.csproj --no-restore
            dotnet build Package.Shared.Entities/Package.Shared.Entities.csproj --no-restore
            dotnet build Package.Shared.Services/Package.Shared.Services.csproj --no-restore
            
        - name: Run bUnit tests
          run: dotnet test Package.Shared.BlazorComponents.UnitTests.csproj --no-build --verbosity minimal
          working-directory: Package.Shared.BlazorComponents.UnitTests

        


            
  playwright-browser-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      
    # Fix xUnit dependency conflict
      - name: Fix package dependencies
        run: |
          dotnet add Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj package xunit.extensibility.core --version 2.8.0
    
    # Selectively restore the test projects
      - name: Restore test projects
        run: |
          dotnet restore Test.Components/Test.Components.csproj
          dotnet restore Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj
          dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host/Test.BrowserBased.Host.csproj
          dotnet restore Test.BrowserBased.Host/Test.BrowserBased.Host.Client/Test.BrowserBased.Host.Client.csproj
    
      - name: Build & Install
        run: | 
          dotnet build Test.BrowserBased.UnitE2ETests/Test.BrowserBased.UnitE2ETests.csproj --no-restore

      - name: Ensure browsers are installed
        run: pwsh Test.BrowserBased.UnitE2ETests/bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Playwright test run excepted filtered
        run: dotnet test --filter "Category!=LocalOnly & Category!=HeadlessFalse" Test.BrowserBased.UnitE2ETests.csproj --no-restore --verbosity minimal
        working-directory: Test.BrowserBased.UnitE2ETests
        
      - name: Debug List All Files in Test Project
        if: always()
        run: ls -R Test.BrowserBased.UnitE2ETests || true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: Test.BrowserBased.UnitE2ETests/playwright-report/
          retention-days: 30
